import React, {useState, useEffect, useContext, Suspense, lazy} from "react";
import "./Project.scss";
import Button from "../../components/button/Button";
import {openSource, socialMediaLinks} from "../../portfolio";
import StyleContext from "../../contexts/StyleContext";
import Loading from "../../containers/loading/Loading";
import {fetchPublicRepos} from "../../utils";
export default function Projects() {
  const GithubRepoCard = lazy(() =>
    import("../../components/githubRepoCard/GithubRepoCard")
  );
  const FailedLoading = () => null;
  const renderLoader = () => <Loading />;
  const [repo, setrepo] = useState([]);
  // todo: remove useContex because is not supported
  const {isDark} = useContext(StyleContext);

  useEffect(() => {
    const getRepoData = () => {
      // public/profile.json is only generated by `node fetch.js` when a GitHub
      // token is configured. Skip straight to the public REST API otherwise so
      // we don't fire a guaranteed 404 on every page load.
      const profileJsonRequest = openSource.useProfileJson
        ? fetch(`${process.env.PUBLIC_URL}/profile.json`)
        : Promise.reject(new Error("profile.json disabled"));

      profileJsonRequest
        .then(result => {
          if (result.ok) {
            return result.json();
          }
          throw result;
        })
        .then(response => {
          setrepoFunction(response.data.user.pinnedItems.edges);
        })
        .catch(() => {
          // Fall back to the token-free public REST API so the section still
          // renders real repositories.
          if (!openSource.githubUsername) {
            console.error(
              "Nothing is shown in place of the Open Source Projects section. Also check if the Projects section has been configured"
            );
            setrepoFunction("Error");
            return;
          }
          fetchPublicRepos(openSource.githubUsername)
            .then(setrepoFunction)
            .catch(function (error) {
              console.error(
                `${error} (because of this error, nothing is shown in place of Projects section. Also check if Projects section has been configured)`
              );
              setrepoFunction("Error");
            });
        });
    };
    getRepoData();
  }, []);

  function setrepoFunction(array) {
    setrepo(array);
  }
  if (
    !(typeof repo === "string" || repo instanceof String) &&
    openSource.display
  ) {
    return (
      <Suspense fallback={renderLoader()}>
        <div className="main" id="opensource">
          <h1 className="project-title">Open Source Projects</h1>
          <div className="repo-cards-div-main">
            {repo.map((v, i) => {
              if (!v) {
                console.error(
                  `Github Object for repository number : ${i} is undefined`
                );
              }
              return (
                <GithubRepoCard repo={v} key={v.node.id} isDark={isDark} />
              );
            })}
          </div>
          <Button
            text={"More Projects"}
            className="project-button"
            href={socialMediaLinks.github}
            newTab={true}
          />
        </div>
      </Suspense>
    );
  } else {
    return <FailedLoading />;
  }
}
