export const formatFileSizeDisplay = value => {
  if (value < 1024) {
    return `${value} KB`;
  }
  return `${parseFloat((value / 1024).toFixed(1))} MB`;
};

// Color values GitHub uses for the most common languages. Only needed by the
// REST fallback below - the GraphQL payload already returns a color per repo.
const LANGUAGE_COLORS = {
  JavaScript: "#f1e05a",
  TypeScript: "#3178c6",
  PHP: "#4F5D95",
  Python: "#3572A5",
  C: "#555555",
  "C#": "#178600",
  "C++": "#f34b7d",
  HTML: "#e34c26",
  CSS: "#563d7c",
  SCSS: "#c6538c",
  Blade: "#f7523f",
  Kotlin: "#A97BFF",
  Swift: "#F05138",
  Ruby: "#701516",
  Java: "#b07219",
  Dart: "#00B4AB",
  Shell: "#89e051",
  Vue: "#41b883",
  Go: "#00ADD8"
};

const DEFAULT_LANGUAGE_COLOR = "#6c63ff";

/**
 * Maps a repository from the public GitHub REST API (/users/:user/repos) into
 * the same shape as the GraphQL "pinnedItems.edges" payload, so that
 * GithubRepoCard can render either source without modification.
 */
export const mapRestRepoToRepoCard = repo => ({
  node: {
    id: repo.id,
    name: repo.name,
    description: repo.description,
    url: repo.html_url,
    forkCount: repo.forks_count,
    stargazers: {totalCount: repo.stargazers_count},
    diskUsage: repo.size, // both the REST "size" and GraphQL "diskUsage" are in KB
    primaryLanguage: repo.language
      ? {
          name: repo.language,
          color: LANGUAGE_COLORS[repo.language] || DEFAULT_LANGUAGE_COLOR
        }
      : null
  }
});

/**
 * Fetches a user's public repositories from the GitHub REST API. This requires
 * no token, which means the Open Source section still works when
 * public/profile.json has not been generated by `node fetch.js`.
 */
export const fetchPublicRepos = (username, limit = 6) => {
  const url = `https://api.github.com/users/${encodeURIComponent(
    username
  )}/repos?per_page=100&sort=pushed`;

  return fetch(url)
    .then(result => {
      if (!result.ok) {
        throw result;
      }
      return result.json();
    })
    .then(repos =>
      repos
        // Skip forks and the special <username>/<username> profile README repo.
        .filter(
          repo =>
            !repo.fork && repo.name.toLowerCase() !== username.toLowerCase()
        )
        .slice(0, limit)
        .map(mapRestRepoToRepoCard)
    );
};
